### ISSUE TITLE
libdmtx causes process to exit with code 40 on bad image

### ISSUE THREAD

**Issue by jbweston** [dmtx/libdmtx#16]
## Description
I have noticed that when attempting to decode a particular image (which does not contain a Datamatrix) `libdmtx` will kill the current process with exit code 40.

## Steps to reproduce

The error is seen when using the [pylibdmtx](https://github.com/NaturalHistoryMuseum/pylibdmtx/tree/master/pylibdmtx) wrapper. Even though the presence of this bug could indicate bad usage of `libdmtx` by the wrapper, I am opening the issue here as well, as I believe this to be a bug in libdmtx itself.

### System info

**OS**: Debian GNU/Linux testing (buster) x86_64
**libdmtx version**: `0.7.4` (reported by `apt info` as `0.7.4-2+b1`
**Python version**: 3.6.0
**pylibdmtx version**:  `0.1.7`
**PIL version**: `5.0.0`

Run the following in a Python interpreter:
```python
from PIL import Image
from pylibdmtx import pylibdmtx
pylibdmtx.decode(Image.open('bad_image.png'))
```
with the following image saved as `bad_image.png` in the current working directory;
![bad_image](https://user-images.githubusercontent.com/6654709/43106381-f7ea099c-8ec7-11e8-8730-4ce4f2c799df.png)

## Expected behavior
An error  should be raised at the Python level

## Observed Behavior
Python process exits with code 40

## Additional information
It seems that [DecodeSchemeBase256](https://github.com/dmtx/libdmtx/blob/4eaac85e1cac5d6810e65624e64d1821155e8ddc/dmtxdecodescheme.c#L518) calls `exit()` when it detects a problem. 

I note that removing calls to `exit` and `assert` is on the roadmap for the 0.8.0 release. I would imagine that removing at least this call to `exit` would require deciding how `DecodeSchemeBase256` should handle error conditions (e.g. returning a null pointer) and plumbing this choice through all the call sites. If given a bit of guidance I would be willing to implement this.

**Comment by jbweston** [comment]
FYI, I've opened [this issue](https://github.com/NaturalHistoryMuseum/pylibdmtx/issues/25) on the downstream wrapper.

**Comment by lprfacial247** [comment]
I have also faced same issue when use pylibdmtx.
But I could not find the solution how can over the issue.
Could you let me know the method how can fix this issue?

**Comment by msva** [comment]
You need to build most recent version of libdmtx.

You can either build version from git or take a 0.7.7 release I just tagged.
