### ISSUE TITLE
new release of libdmtx ?

### ISSUE THREAD

**Issue by shirishag75** [dmtx/libdmtx#25]
Could we have a new release of libdmtx so that the issue shared in #21 is resolved. The patch has already been integrated into the master.

**Comment by markemus** [comment]
I also hope this happens soon for #16 .

**Comment by shirishag75** [comment]
Also dunno how or if any effect it will have as python3 is the new lord. 

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=942106

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931659

**Comment by darouwan** [comment]
It seem no new release for 0.7.6 in 2021 yet.

**Comment by msva** [comment]
@darouwan actually, there is not anough testing of git version to make sure it is ready to release.
IIRC, there was some issues that made it to crash in some crcumstances.
Unfortunatelly, I've not enough spare time to work on it ATM, so any kind of help is welcome.

**Comment by mattbucci** [comment]
[v0.7.7](https://github.com/dmtx/libdmtx/releases/tag/v0.7.7) was released so I guess this can be closed
