### ISSUE TITLE
not able to read datamatrix

### ISSUE THREAD

**Issue by bsdis** [dmtx/libdmtx#30]
Does anyone have an idea why I cannot read this QR code using libdmtx software? I dont think the quality of the image is that bad... https://i.ibb.co/FnQkcSL/platedmtrx.png

**Comment by nikolaitasev** [comment]
First it is a Datamatrix not QR code. The problem is most probably the quality, try to binarize the image and than pass it to the library. Also you need to have at least one module empty space on each side.

**Comment by bsdis** [comment]
Hi, even this binarized image is not being decoded: 
https://i.ibb.co/Gk7sFZ1/Screen-Shot-2019-06-09-at-17-44-53.png
Why?

**Comment by msva** [comment]
> Hi, even this binarized image is not being decoded:
> https://i.ibb.co/Gk7sFZ1/Screen-Shot-2019-06-09-at-17-44-53.png
> Why?

Does your goal is to read the content of exactly this matrix (once), and then 
forget about it, or do you want to build some algorythm to read many more 
matrixes like that?

In case of the former one, I can decode it for you (it's not a big matrix and 
I can do what I described below).

In case of the latter one, it's a bit complicated..

Well, the main reason of impossibility to decode this matrix, imo, is that it 
is very "dirty" (some cells have different width/height, some of them are even 
shifted a bit).

So, talking honestly, that make it to be a not-a-matrix-at-all for decoding 
algorythm, but something-that-looks-like-matrix to you.

If you'll make a real matrix with "valid" cells, colored with a pattern of 
your given "matrix", I bet decoder will read it.

**Comment by msva** [comment]
Well, it is also few things, aht can be the reason of failing to decode.
One of them, say, is a wrong "checksum".

**Comment by msva** [comment]
Btw, talking about terminology.
"Binarization" is not just making it b/w. It is more like "making it easier to decoder to represent cells like binary code". And there, well, should be cells (square ones), although decoder allows some deviation, but there is no magic exists in the world, so decoder can't perform the miracle.
I've properly binarized your initial (soldered) matrix, and got the "8205279" as decoding result:
![image](https://user-images.githubusercontent.com/268102/59165808-383e3900-8b2a-11e9-84a5-eb9b2e6c3719.png)

Although, your second image looks like the broken one (maybe, it is either randomly picked "pseudocells", or some "pseudocells" was colored by mistake (or even some of them are missing)).

**Comment by shm0nya** [comment]
I don`t know where place this
https://github.com/dmtx/libdmtx/wiki/Repair-Error

I found error. May be it can fix this
